GRANT USAGE ON SCHEMA franchise TO franchise_app;
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA franchise
    TO franchise_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA franchise
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO franchise_app;
